# Generated by Django 2.2.2 on 2019-06-27 23:06

from django.db import migrations, models

import json


def add_to_database(apps, schema_editor):
    Mineral = apps.get_model('minerals', 'Mineral')
    with open('assets/data/minerals.json') as data:
        minerals = json.load(data)
    
    for mineral in minerals:
        for key, value in mineral.items():
            mineral[key] = value.replace('\\u', '&#x')
        Mineral.objects.create(**mineral).save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_filename', models.CharField(max_length=255, null=True)),
                ('image_caption', models.TextField(null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('formula', models.TextField(null=True)),
                ('strunz_classification', models.CharField(max_length=255, null=True)),
                ('color', models.TextField(null=True)),
                ('crystal_system', models.CharField(max_length=255, null=True)),
                ('unit_cell', models.TextField(null=True)),
                ('crystal_symmetry', models.CharField(max_length=255, null=True)),
                ('cleavage', models.CharField(max_length=255, null=True)),
                ('mohs_scale_hardness', models.CharField(max_length=255, null=True)),
                ('luster', models.CharField(max_length=255, null=True)),
                ('streak', models.CharField(max_length=255, null=True)),
                ('diaphaneity', models.CharField(max_length=255, null=True)),
                ('optical_properties', models.CharField(max_length=255, null=True)),
                ('refractive_index', models.CharField(max_length=255, null=True)),
                ('crystal_habit', models.TextField(blank=True)),
                ('specific_gravity', models.CharField(max_length=255, null=True)),
                ('group', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RunPython(add_to_database),
    ]
