# Generated by Django 2.2.2 on 2019-06-07 19:34
from django.db import migrations, models

import json


def add_to_database(apps, schema_editor):
    Mineral = apps.get_model('minerals', 'Mineral')
    with open('assets/data/minerals.json') as data:
        minerals = json.load(data)
    
    for mineral in minerals:
        for key, value in mineral.items():
            mineral[key] = value.replace('\\u', '&#x')
        Mineral.objects.create(**mineral).save()


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0002_auto_20190607_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='group',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.RunPython(add_to_database),
    ]
